name: Deploy to Production

on:
  push:
    tags:
      - '*'

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'
        
    - name: Install dependencies
      run: npm install
      
    - name: Build application
      run: npm run build
      
    - name: Deploy to production
      uses: easingthemes/ssh-deploy@v2.1.8
      with:
        server: ${{ secrets.PRODUCTION_SERVER }}
        username: ${{ secrets.PRODUCTION_USERNAME }}
        key: ${{ secrets.PRODUCTION_SSH_KEY }}
        port: ${{ secrets.PRODUCTION_PORT }}
        local_path: 'build'
        remote_path: '/var/www/your-app'
        
    - name: Push to prod branch
      run: git push origin HEAD:prod
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
